### ISSUE TITLE
[BUG] "Set music to be played inside dungeons/raids" not playing any music at all

### ISSUE THREAD

**Issue by Sylveightysubtle** [Zidras/DBM-Warmane#95]
**Describe the bug**
When zoning into an instance, the default music for it plays and not the music set, it does not work when zoning in manually and zoning in from RDF. 

**DBM Version**
7.09

**To Reproduce**
1. Type /dbm
2. Go to "Event Sounds"
3. Change "Set music to be played inside dungeons/raids" to Ulduar: Titan Orchestra or any other music
4. Zone into dungeon/raid

**Expected behavior**
The set music should start to play after zoning in.

**Video**
(https://streamable.com/1s7sao)

**Additional context**
Most of the other ones (Victory sound, Played during encounters, Encounter engage. I haven't checked encounter defeat yet) work. 

**Error Log**

```

```

**Comment by Zidras** [comment]
As stated on the commit description, this will not be perfect since there's no event for Loading Screens, so it will stop whatever music is playing, and play game music file instead. I considered running this new function on ZONE_CHANDED_INDOORS/ZONE_CHANGED events, but the result was very jarring, with music stopping and starting on quick succession, since subzones are very common inside instances and very easy to trigger these events multiple times (ICC, for example, will suffer from this imperfection due to portals having loading screen). Tried incorporating self.Options.musicPlaying but it would suffer from the same problem of not having a nil switch on loading screens.
